# Generated by Django 5.1.3 on 2024-12-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'verbose_name': 'Evento', 'verbose_name_plural': 'Eventos Deportivos'},
        ),
        migrations.AlterField(
            model_name='evento',
            name='hora',
            field=models.TimeField(verbose_name='Hora de realizacion'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Correo electronico'),
        ),
    ]
